name: Test django blog

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker-Compose (with .env)
        run: docker compose -f docker-compose-stage.yml up -d --build
      - name: Run Tests (with .env)
        run: docker compose -f docker-compose-stage.yml exec backend sh -c "cd ./core && uv run pytest ."
  deploy:
    runs-on: ubuntu-latest
    needs: test
    name: Deploy
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Connect and Execute Commands
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.ARVAN_USER}}
        host: ${{secrets.ARVAN_HOST}}
        script: |
          cd ${{secrets.DEPLOY_PATH}}
          docker-compose -f docker-compose-stage.yml stop
          git pull
          docker-compose -f docker-compose-stage.yml restart
          "
